---
GENERATOR_VERSION: '1.0'

ANSIBLE_METADATA: |
    {
        'metadata_version': '1.1',
        'status': ['preview'],
        'supported_by': 'network'
    }

NETWORK_OS: iosxr
RESOURCE: static_routes
COPYRIGHT: Copyright 2019 Red Hat

DOCUMENTATION: |
  module: iosxr_static_routes
  version_added: 2.10
  short_description: Manage static routes on devices running Cisco IOS-XR.
  description: 
    - This module manages static routes on devices running Cisco IOS-XR.
  author: Nilashish Chakraborty (@Nilashishc)
  options:
    config:
      description: A dictionary of static route options.
      type: list
      elements: dict
      suboptions:
        vrf:
          description:
            - The VRF to which the static route(s) belong.
          type: str
          default: __global__
        address_families:
          description: A dictionary specifying the address family to which the static route(s) belong.
          type: list
          elements: dict
          suboptions:
            afi:
              description:
                - Specifies the top level address family indicator.
              type: str
              choices: ['ipv4', 'ipv6']
              required: True
            safi:
              description:
                - Specifies the subsequent address family indicator.
              type: str
              choices: ['unicast', 'multicast']
              required: True
            routes:
              description: A dictionary that specifies the static route configurations.
              elements: dict
              type: list
              suboptions:
                dest:
                  description:
                    - An IPv4 or IPv6 address in CIDR notation that specifies the destination network for the static route.
                  type: str
                  required: True
                  next_hops:
                  description:
                    - Next hops to the specified destination.
                  type: list
                  elements: dict
                  suboptions:
                    forward_router_address:
                      description: 
                        - The IP address of the next hop that can be used to reach the destination network. 
                      type: str
                    interface:
                      description:
                        - The interface to use to reach the destination.
                      type: str
                    vrf:
                      description:
                        - The destination VRF.
                      type: str
                    admin_distance:
                      description:
                        - The administrative distance for this static route.
                        - Refer to vendor documentation for valid values.
                      type: int
                    metric:
                      description:
                        - Specifes the metric for this static route.
                        - Refer to vendor documentation for valid values.
                      type: int
                    description:
                      description:
                        - Specifies the description for this static route.
                      type: str
                    vrflabel:
                      description:
                        - Specifies the VRF label for this static route.
                        - Refer to vendor documentation for valid values.
                      type: int
                    permanent:
                      description:
                        - Specifies whether or not this is a permanent route.
                      type: bool
                    tag:
                      description:
                        - Specifies a numeric tag for this static route.
                        - Refer to vendor documentation for valid values.
                      type: int
                    track:
                      description:
                        - Specifies the object to be tracked.
                        - This enables object tracking for static routes.
                      type: str 
                    tunnel_id:
                      description:
                        - Specifies a tunnel id for the route.
                        - Refer to vendor documentation for valid values.
                      type: int
    state:
      description:
        - The state the configuration should be left in.
      type: str
      choices:
      - merged
      - replaced
      - overridden
      - deleted
      - gathered
      - rendered
      default: merged

EXAMPLES:
  - merged_example_01.txt
  - replaced_example_01.txt
  - overridden_example_01.txt
  - deleted_example_01.txt
  - gathered_example_01.txt
  - rendered_example_01.txt
